{"links": {"self": {"href": "data/repositories/dedalus-project/dedalus/pullrequests/33/comments/9685257.json"}, "html": {"href": "#!/dedalus-project/dedalus/pull-requests/33/_/diff#comment-9685257"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 33, "links": {"self": {"href": "data/repositories/dedalus-project/dedalus/pullrequests/33.json"}, "html": {"href": "#!/dedalus-project/dedalus/pull-requests/33"}}, "title": "Basic restarting capability & example"}, "content": {"raw": "When I tried running this with one of my scripts, the CFL calculation threw an error:\n\nTraceback (most recent call last):\n  File \"anelastic_radconv_kburns.py\", line 419, in <module>\n    dt = CFL.compute_dt()\n  File \"/u/dlecoane/kburns/dedalus/dedalus/extras/flow_tools.py\", line 203, in compute_dt\n    max_global_freq = self.reducer.global_max(local_freqs)\n  File \"/u/dlecoane/kburns/dedalus/dedalus/extras/flow_tools.py\", line 51, in global_max\n    if data.size:\nAttributeError: 'int' object has no attribute 'size'\n\nThis happens when we try to calculate a CFL before taking a timestep.  This is not a problem for simulations which start on iteration 0 because the CFL routine checks to see if iteration=0, if so, it just uses the stored_dt.  I fix this by instead checking if iteration==self.first_iteration, where I set self.first_iteration = self.iteration on initialization.  Might be useful to include this in this PR.  Not sure why this issue doesn't come up for the RB test you included.", "markup": "markdown", "html": "<p>When I tried running this with one of my scripts, the CFL calculation threw an error:</p>\n<p>Traceback (most recent call last):\n  File \"anelastic_radconv_kburns.py\", line 419, in &lt;module&gt;\n    dt = CFL.compute_dt()\n  File \"/u/dlecoane/kburns/dedalus/dedalus/extras/flow_tools.py\", line 203, in compute_dt\n    max_global_freq = self.reducer.global_max(local_freqs)\n  File \"/u/dlecoane/kburns/dedalus/dedalus/extras/flow_tools.py\", line 51, in global_max\n    if data.size:\nAttributeError: 'int' object has no attribute 'size'</p>\n<p>This happens when we try to calculate a CFL before taking a timestep.  This is not a problem for simulations which start on iteration 0 because the CFL routine checks to see if iteration=0, if so, it just uses the stored_dt.  I fix this by instead checking if iteration==self.first_iteration, where I set self.first_iteration = self.iteration on initialization.  Might be useful to include this in this PR.  Not sure why this issue doesn't come up for the RB test you included.</p>", "type": "rendered"}, "created_on": "2015-09-07T05:54:20.483099+00:00", "user": {"display_name": "Daniel Lecoanet", "uuid": "{0ff8d177-8703-4f25-93d4-68857e948a31}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B0ff8d177-8703-4f25-93d4-68857e948a31%7D"}, "html": {"href": "https://bitbucket.org/%7B0ff8d177-8703-4f25-93d4-68857e948a31%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/829d5ddfabf278a6c21111d4de2fe031d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsDL-3.png"}}, "nickname": "lecoanet", "type": "user", "account_id": "557058:ba5c14ee-54e1-4d72-aa9e-1e2a4c5ab718"}, "updated_on": "2015-09-07T05:54:20.487697+00:00", "type": "pullrequest_comment", "id": 9685257}