{"links": {"self": {"href": "data/repositories/dedalus-project/dedalus/issues/64/comments/52948311.json"}, "html": {"href": "#!/dedalus-project/dedalus/issues/64#comment-52948311"}}, "issue": {"links": {"self": {"href": "data/repositories/dedalus-project/dedalus/issues/64.json"}}, "type": "issue", "id": 64, "repository": {"links": {"self": {"href": "data/repositories/dedalus-project/dedalus.json"}, "html": {"href": "#!/dedalus-project/dedalus"}, "avatar": {"href": "data/bytebucket.org/ravatar/{1dc39ab6-2798-450d-af2f-e976f94b5794}ts=2009435"}}, "type": "repository", "name": "dedalus", "full_name": "dedalus-project/dedalus", "uuid": "{1dc39ab6-2798-450d-af2f-e976f94b5794}"}, "title": "NCCs cause strange MPI crashes after commit 4232435 in 3D domains with distributed processor meshes"}, "content": {"raw": "Jeff and I took a look at this, and unfortunately we\u2019re worried that it\u2019s some kind of stack problem.  From the trace, it looks like the error is actually happening when the outputs are being created, not during the NCC creation.  It\u2019s puzzling because that commit doesn\u2019t alter evaluator.py and it doesn\u2019t change the broadcasting behavior of the NCC computation \\(which already uses uppercase Bcast\\).  \n\nAlso, I\u2019m able to run both scripts fine with 4 processes on the Flatiron cluster.  Can you reproduce the error with a different stack?  In particular, what version of hdf5 are you using for this one?  I\u2019m getting some weird hdf5 errors with 1.10\\+ on the Flatiron cluster, but version 1.8\\+ works fine.", "markup": "markdown", "html": "<p>Jeff and I took a look at this, and unfortunately we\u2019re worried that it\u2019s some kind of stack problem.  From the trace, it looks like the error is actually happening when the outputs are being created, not during the NCC creation.  It\u2019s puzzling because that commit doesn\u2019t alter evaluator.py and it doesn\u2019t change the broadcasting behavior of the NCC computation (which already uses uppercase Bcast).  </p>\n<p>Also, I\u2019m able to run both scripts fine with 4 processes on the Flatiron cluster.  Can you reproduce the error with a different stack?  In particular, what version of hdf5 are you using for this one?  I\u2019m getting some weird hdf5 errors with 1.10+ on the Flatiron cluster, but version 1.8+ works fine.</p>", "type": "rendered"}, "created_on": "2019-07-11T18:27:07.613657+00:00", "user": {"display_name": "Keaton Burns", "uuid": "{3d3e64f1-bf12-45df-b655-4543d8fb34c4}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d3e64f1-bf12-45df-b655-4543d8fb34c4%7D"}, "html": {"href": "https://bitbucket.org/%7B3d3e64f1-bf12-45df-b655-4543d8fb34c4%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:e31a7835-5317-4dfa-8551-f32a06f40279/40f33f99-2b75-4a17-a8c2-07c8d74c7480/128"}}, "nickname": "kburns", "type": "user", "account_id": "557058:e31a7835-5317-4dfa-8551-f32a06f40279"}, "updated_on": null, "type": "issue_comment", "id": 52948311}